name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Install-libraries:
    name: Install libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: install dependencies
        run: npm install
  Test-angular-app:
    name: Test angular app
    runs-on: ubuntu-latest
    steps:
      - name: Test angular app
        run: npm run test
    needs: [Install-libraries]
  Build-angular-app:
    name: Build angular app
    runs-on: ubuntu-latest
    needs: [Test-angular-app]
    steps:
      - name: Build angular app
        run: npm run build
      - name: Capacitor sync
        run: npx cap sync
  Build-app-bundle:
    name: Build app bundle
    runs-on: ubuntu-latest
    needs: [Build-angular-app]
    steps:
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Build app bundle
        run: cd android && ./gradlew bundle && ./gradlew assembleDebug

